version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: monetization_postgres
    environment:
      POSTGRES_USER: monetization_user
      POSTGRES_PASSWORD: monetization_pass
      POSTGRES_DB: monetization_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: